### PR TITLE
Preload Precise engine and model

### PR DESCRIPTION
**Pull request by krisgesling**
This packages the Precise engine and default model in the image so it doesn't need to be downloaded on first boot.

Is stage 1 of #29

### CODE REVIEW

**Comment by krisgesling** [comment]
Just realised that in core we don't actually check if the Precise binary already exists. The first time it runs, it's always downloaded. Preloading without this update still provides a better experience on first boot but then arbitrarily performs a big and useless download.

**Comment by forslund** [comment]
petact shouldn't do that if the tar.gz exists and is correct.

Could the problem here be that the tar.gz is extracted but not kept?

**Comment by krisgesling** [comment]
Ah petact does that internally, that makes sense. Will amend to leave the tar.gz in place

**Comment by forslund** [comment]
Yeah the `install_package()` function should download the md5, compare with the existing tar.gz if it's different go a head with the install otherwise just return

**Comment by forslund** [comment]
Hmm, I had some issues with this:

```
2020/11/03 20:40:48 ==== run ====
2020/11/03 20:40:49 tar -xzf /home/mycroft/.mycroft/precise/precise-engine_0.3.0_aarch64.tar.gz | tar (child): /home/mycroft/.mycroft/precise/precise-engine_0.3.0_aarch64.tar.gz: Cannot open: Not a directory
2020/11/03 20:40:49 tar -xzf /home/mycroft/.mycroft/precise/precise-engine_0.3.0_aarch64.tar.gz | tar (child): Error is not recoverable: exiting now
2020/11/03 20:40:49 tar -xzf /home/mycroft/.mycroft/precise/precise-engine_0.3.0_aarch64.tar.gz | 
2020/11/03 20:40:49 tar -xzf /home/mycroft/.mycroft/precise/precise-engine_0.3.0_aarch64.tar.gz | gzip: stdin: unexpected end of file
2020/11/03 20:40:49 tar -xzf /home/mycroft/.mycroft/precise/precise-engine_0.3.0_aarch64.tar.gz | /usr/bin/tar: Child returned status 2
2020/11/03 20:40:49 tar -xzf /home/mycroft/.mycroft/precise/precise-engine_0.3.0_aarch64.tar.gz | /usr/bin/tar: Error is not recoverable: exiting now
2020/11/03 20:40:49 Action `recipe` failed at stage Run, error: exit status 2
```

gonna see if it works better if the command line if I add `-C /home/mycroft/.mycroft/precise/` to the command line to specify the extraction point.

**Comment by krisgesling** [comment]
yeah sorry, i was using this to get it across to a build machine to test but got the same and gave up for the night

**Comment by forslund** [comment]
Ah gotcha.

My machine isn't very happy with me right now. Simultaneously running the image-building-script and encoding a let's play video :)

**Comment by krisgesling** [comment]
alright, this should work now :+1:

**Comment by forslund** [comment]
Looks good!

Wonder if we should do the same with the model's tar.gz as well?

**Comment by krisgesling** [comment]
damn early morning git... will fix up later today

**Comment by krisgesling** [comment]
Given it started getting a little long, I thought it was worth splitting the Precise loading out to it's own recipe. Really just for clarity at this stage but could see in the future wanting or not wanting it included in a build.

**Comment by krisgesling** [comment]
If there are no objections I'm going to merge this and PR #33

**Pull request merged**
